FROM python:3.11-slim

WORKDIR /app

#Copy required files
COPY ../requirements.txt /app/
COPY src/__init__.py /app/src/
COPY src/inference_classification.py /app/src/
COPY src/lambda_func.py /app/src/
COPY ../output/model/roberta-finetuned-model/final_model/ /app/model/
COPY ../data/label_mapping.json /app/label_mapping.json

#Install dependencies
RUN pip install awslambdaric
RUN pip install -r requirements.txt

#Make script readable and execuatble
RUN chmod -R a+rX /app

#Set lambda function 
ENTRYPOINT ["/usr/local/bin/python", "-m", "awslambdaric"]
CMD ["src.lambda_function.lambda_function"]