FROM python:3.11-slim

WORKDIR /app

#Copy required files
COPY ../requirements.txt /app/
COPY src/__init__.py /app/src/
COPY src/inference_generation.py /app/src/
COPY src/lambda_func_seq.py /app/src/
COPY ../output/model/flan-t5-finetuned/final_merged_model/ /app/model/

#Install dependencies
RUN pip install awslambdaric
RUN pip install --no-cache-dir -r requirements.txt

#Make script readable and execuatble
RUN chmod -R a+rX /app

#Set lambda function 
ENTRYPOINT ["/usr/local/bin/python", "-m", "awslambdaric"]
CMD ["src.lambda_function.lambda_function"]